# Generated by Django 3.0.3 on 2020-02-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
    ]
