# Generated by Django 3.0.3 on 2020-02-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200221_0012'),
        ('classes', '0002_auto_20200221_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
