# Generated by Django 2.2.6 on 2020-04-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Yet', 'ยังไม่บริจาค'), ('Pending', 'รอการยืนยัน'), ('Recieve', 'ได้รับของบริจาค')], default='Yet', max_length=20)),
                ('desc', models.TextField()),
                ('condition', models.CharField(choices=[('1', 'ชำรุด'), ('2', 'ต้องซ่อม'), ('3', 'ดี'), ('4', 'เสมือนใหม่'), ('5', 'ใหม่')], max_length=1)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now=True)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Album')),
                ('donor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.Doner')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('_type', models.CharField(choices=[('feedback', 'การตอบกลับ'), ('shipping', 'การขนส่ง'), ('update', 'การอัปเดต')], default='update', max_length=10)),
                ('ladtitude', models.CharField(max_length=50)),
                ('longtitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SendDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('EMS', 'ส่งทางไปรษณีย์'), ('SELF', 'ไปส่งที่ผุ้รับด้วยตัวเอง'), ('TAKEHOME', 'ผุ้รับมารับ'), ('TRANFER', 'โอนเงิน')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=50)),
                ('company', models.CharField(choices=[('THAIPOST', 'ไปรษณีย์ไทย'), ('KERRY', 'เคอรรี่'), ('FLASH', 'เเฟลช')], max_length=8)),
                ('reciept', models.ImageField(upload_to='shipping/slip/')),
                ('send_datetime', models.DateTimeField()),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.Location')),
                ('senddetail', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.SendDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_flag', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=32, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('propose', models.CharField(max_length=255)),
                ('helping_people', models.SmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'เปิดรับริจาค'), ('close', 'ปิดรับบริจาค'), ('process', 'ดำเนินการ'), ('finished', 'เสร็จสิ้น')], max_length=10)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateTimeField()),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Album')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Location')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Recipient')),
                ('requiretype', models.ManyToManyField(to='donations.RequireType')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('url', models.ImageField(upload_to='album/pic/')),
                ('album', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=40)),
                ('detail', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Album')),
                ('donation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.Donation')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Location')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Recipient')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='dtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.RequireType'),
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Location'),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
    ]
