# Generated by Django 2.2.6 on 2020-03-31 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0005_auto_20200331_2148'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Recipient'),
        ),
        migrations.AddField(
            model_name='project',
            name='requiretype',
            field=models.ManyToManyField(to='donations.RequireType'),
        ),
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Album'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Location'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Recipient'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Doner'),
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Location'),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
        migrations.AddField(
            model_name='album',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
    ]
