# Generated by Django 2.2.6 on 2020-03-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('donations', '0002_album_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.Doner'),
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Location'),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Location'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Recipient'),
        ),
        migrations.AddField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.Album'),
        ),
        migrations.AddField(
            model_name='project',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Recipient'),
        ),
        migrations.AddField(
            model_name='project',
            name='requiretype',
            field=models.ManyToManyField(to='donations.RequireType'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Yet', 'ยังไม่บริจาค'), ('Pending', 'รอการยืนยัน'), ('Recieve', 'ได้รับของบริจาค')], default=('Yet', 'ยังไม่บริจาค'), max_length=20),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.Location'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='senddetail',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='donations.SendDetail'),
        ),
    ]
