# Generated by Django 2.2.6 on 2020-03-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20200401_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
