# Generated by Django 2.2.6 on 2020-04-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20200401_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Project'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Yet', 'ยังไม่บริจาค'), ('Pending', 'รอการยืนยัน'), ('Recieve', 'ได้รับของบริจาค')], default='Yet', max_length=20),
        ),
    ]
