# Generated by Django 2.2.6 on 2020-04-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20200403_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='_type',
            new_name='dtype',
        ),
    ]
