# Generated by Django 2.2.6 on 2020-04-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20200403_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='dtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.RequireType'),
        ),
    ]
