# Generated by Django 2.2.6 on 2020-04-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20200408_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiretype',
            name='amount',
        ),
    ]
