# Generated by Django 2.2.6 on 2020-04-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_remove_requiretype_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Album'),
        ),
    ]
