# Generated by Django 2.2.6 on 2020-04-08 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20200408_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
