# Generated by Django 2.2.6 on 2020-04-17 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_project_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
