# Generated by Django 2.2.6 on 2020-04-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20200417_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='use_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='value',
            field=models.CharField(max_length=32),
        ),
    ]
