# Generated by Django 2.2.6 on 2020-04-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20200417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='value',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
