# Generated by Django 3.0.3 on 2020-02-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='reciever',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
