# Generated by Django 3.0.3 on 2020-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200221_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='is_accept',
            field=models.BooleanField(null=True),
        ),
    ]
