# Generated by Django 3.0.3 on 2020-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200226_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='is_accept',
            field=models.BooleanField(default=True),
        ),
    ]
