# Generated by Django 3.0.3 on 2020-02-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200221_0012'),
        ('management', '0005_auto_20200212_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
